//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhub_2._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LREntities : DbContext
    {
        public LREntities()
            : base("name=LREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material> Material { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductMaterial> ProductMaterial { get; set; }
        public DbSet<Shop> Shop { get; set; }
        public DbSet<TypeMaterial> TypeMaterial { get; set; }
        public DbSet<TypeProduct> TypeProduct { get; set; }
        public DbSet<Unit> Unit { get; set; }
    }
}
