//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhub_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> idTypeProduct { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> idShop { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
